[build]
  command = "npm install && npm run build"  # Adjust this to your build command

[build.environment]
  RUST_VERSION = "stable"  # Set the Rust version you specified in the rust-toolchain file

[build.environment.variables]
  CARGO_HOME = "/opt/buildhome/.cargo"  # Set the Cargo installation path

[build.lifecycle]
  # Install Rust and Cargo
  - command = "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain $RUST_VERSION"
  - command = "export PATH=$CARGO_HOME/bin:$PATH"
